# Generated by Django 2.1.5 on 2019-04-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190421_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='smarthomedevice',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='smarthomedevice',
            name='name',
            field=models.CharField(max_length=75),
        ),
    ]
