# Generated by Django 2.1.5 on 2019-04-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190421_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafile',
            name='data_file_hash',
            field=models.CharField(default='no_hash', max_length=35, unique=True),
            preserve_default=False,
        ),
    ]
