# Generated by Django 2.1.5 on 2019-04-28 21:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_datafile_data_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='data_file',
            field=models.FileField(upload_to='data-files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pcap'])]),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='processed_file',
            field=models.FileField(blank=True, null=True, upload_to='data-files-processed', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
        ),
    ]
