# Generated by Django 2.1.5 on 2019-04-29 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0006_auto_20171214_2232'),
        ('api', '0005_auto_20190428_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCapturingDevice',
            fields=[
                ('oauth_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
            ],
        ),
    ]
