# Generated by Django 2.1.5 on 2019-04-29 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ('api', '0005_auto_20190428_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCapturingDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='datafile',
            name='data_capturing_device',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='api.DataCapturingDevice'),
            preserve_default=False,
        ),
    ]
