# Generated by Django 2.1.5 on 2019-04-29 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_datacapturingdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacapturingdevice',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datafile',
            name='data_capturing_device',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, to='api.DataCapturingDevice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datacapturingdevice',
            name='oauth_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
        ),
    ]
