# Generated by Django 2.1.5 on 2019-05-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190429_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacapturingdevice',
            name='name',
            field=models.CharField(default='Generic capture device', max_length=30),
            preserve_default=False,
        ),
    ]
