# Generated by Django 2.1.5 on 2019-04-30 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190429_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='data_file',
            field=models.FileField(blank=True, null=True, upload_to='data-files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pcap'])]),
        ),
    ]
