# Generated by Django 2.1.5 on 2019-05-07 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_datacapturingdevice_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacapturingdevice',
            name='oauth_application',
        ),
    ]
