# Generated by Django 2.1.5 on 2019-05-08 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_datacapturingdevice_oauth_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='data_file',
            field=models.FileField(upload_to='data-files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pcap', 'csv'])]),
        ),
    ]
