# Generated by Django 2.1.7 on 2019-04-07 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20190406_2027'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Files',
        ),
    ]
