# Generated by Django 2.1.7 on 2019-04-07 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20190406_2029'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='MachineData',
        ),
    ]
